name: ClockIn
on:
  # set cron around 7.30 (UTC+7) // sometimes cron will execute at 8.50, so be carefull to set the schedule
  # * * * * * perintah yang akan dieksekusi
  # – – – – –
  # | | | | |
  # | | | | +—– day of week (0 – 7) (Sunday=0)
  # | | | +——- month (1 – 12)
  # | | +——— day of month (1 – 31)
  # | +———– hour (0 – 23)
  # +————- min (0 – 59)
  #
  #schedule:
      #- cron: "30 0 * * *"
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      # - name: Copy .env file
      #   run: cp .env.example .env
      - name: Storage Permission
        run: chmod -R 777 storage bootstrap
      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Execute artisan
        run: php artisan talenta:clock-in
        env:
          TZ: Asia/Jakarta
          TALENTA_USER_EMAIL: ${{ secrets.TALENTA_EMAIL }}
          TALENTA_USER_PASSWORD: ${{ secrets.TALENTA_PASSWORD }}
          TALENTA_LIVE_ATTENDANCE_LATITUDE: ${{ secrets.LATITUDE }}
          TALENTA_LIVE_ATTENDANCE_LONGITUDE: ${{ secrets.LONGITUDE }}
          TALENTA_USER_ID: ${{ secrets.TALENTA_USER_ID }}
          TALENTA_COMPANY_ID: ${{ secrets.TALENTA_COMPANY_ID }}
          TALENTA_OFF_DAY: saturday,sunday
